name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter Web with secrets
        run: |
          flutter build web \
            --dart-define=ServiceId=${{ secrets.SERVICE_ID }} \
            --dart-define=TemplateId=${{ secrets.TEMPLATE_ID }} \
            --dart-define=PublicKey=${{ secrets.PUBLIC_KEY }} \
            --release \
            --base-href "/portfolio/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true